version: '3.5'

services:
  postgres:
    container_name: db
    
    # ports: "12432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-BestCrockEver78}

  pgadmin:
    container_name: web
    # ports:
    #  - "12480:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@anisfeld.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminko}


volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/.app_data/postgres
  pgadmin:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /var/local/pgadmin
      device: /mnt/storage/.app_data/pgadmin
