version: '3.5'
volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      
      device: ":/mnt/storage/.app_data/postgres"
  pgadmin:
    driver: local
    driver_opts:
      type: none
      device: ":/mnt/storage/.app_data/pgadmin"
