version: '3.5'

services:
  postgres:
    container_name: db
  pgadmin:
    container_name: web

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/.app_data/postgres
  pgadmin:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /var/local/pgadmin
      device: /mnt/storage/.app_data/pgadmin
